"""add stripe fields to users

Revision ID: 6445326fd00c
Revises: 68e4806f2b9e
Create Date: 2026-02-05 20:25:46.582008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6445326fd00c'
down_revision: Union[str, Sequence[str], None] = '68e4806f2b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ✅ 1) Add is_premium with safe default (so existing rows get False)
    op.add_column(
        'users',
        sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )

    # ✅ 2) Add stripe fields (nullable is fine)
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))

    # ✅ 3) Optional: remove server default after backfill
    op.alter_column('users', 'is_premium', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
